# Generated by Django 3.2.9 on 2022-11-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='searched_movies',
            field=models.ManyToManyField(related_name='searched_users', to='movies.Movie'),
        ),
    ]
